# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
    - id: black
      name: check that the code is formatted with black
      entry: pipenv run black --check
      language: system
      types: [python]

    - id: isort
      name: check that the imports are sorted
      entry: pipenv run isort --check
      language: system
      types: [python]
