stages:
  preprocess:
    cmd: python -m dvc_workshop.pipeline.preprocess.preprocessing
      --output-file "data/preprocessed/preprocessed.txt"
    deps:
      - dvc_workshop/pipeline/preprocess
    outs:
      - data/preprocess

  train:
    cmd: python -m dvc_workshop.pipeline.train.training
      --preprocessed-file "data/preprocess/preprocessed.txt"
      --output-file "data/train/model.txt"
    deps:
      - data/preprocess
      - dvc_workshop/pipeline/train
    outs:
      - data/train
    params:
      - params.py:
          - SEED

  evaluate:
    cmd: python -m dvc_workshop.pipeline.evaluate.evaluation
      --model-file "data/train/model.txt"
    deps:
      - data/train
      - dvc_workshop/pipeline/evaluate
