stages:
  download_mnist:
    cmd: python -m dvc_workshop.utils.generate_mnist_dataset --output-image-path data/download_mnist/Images
      --output-df-path data/download_mnist
    deps:
    - dvc_workshop/utils/generate_mnist_dataset.py
    - gs://dvc-workshop-raw/mnist
    outs:
    - data/download_mnist
  preprocess:
    cmd: python -m dvc_workshop.pipeline.preprocess.preprocessing
    deps:
    - data/download_mnist
    - dvc_workshop/pipeline/preprocess/
    params:
    - params.py:
      - PreprocessParams
    outs:
    - data/preprocess
  train:
    cmd: python -m dvc_workshop.pipeline.train.training
    deps:
    - data/preprocess
    - dvc_workshop/pipeline/train
    params:
    - params.py:
      - ModelParams
      - PreprocessParams
    outs:
    - data/train
  evaluate:
    cmd: python -m dvc_workshop.pipeline.evaluate.evaluation
    deps:
    - data/preprocess/
    - data/train
    - dvc_workshop/pipeline/evaluate/
    outs:
    - data/evaluate
