
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install cookiecutter
        run: pip install cookiecutter
      - name: Run cookiecutter with default configuration
        run: cookiecutter --no-input --accept-hooks no .
