name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: VisiumCH/check-python-style@main
        with:
          python-version: "{{ cookiecutter.python_version }}"
